import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Nav from "@/components/nav2";

const chivo = Chivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={chivo.className}>
        <Nav />
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
